version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app
    container_name: frontend-container
    restart: always
    ports:
      - "3000:3000"